spring.application.name=v1
server.port=${SERVER_PORT:2030}

spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/meubolso}
spring.datasource.username=${DB_USER:postgres}
spring.datasource.password=${DB_PASSWORD:postgres}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.jdbc.time_zone=UTC

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

security.jwt.secret=${JWT_SECRET:change-me-to-a-very-long-secret-with-at-least-64-bytes-change-me}
security.jwt.access-token-minutes=${JWT_ACCESS_MINUTES:30}
security.jwt.refresh-token-days=${JWT_REFRESH_DAYS:14}

app.cors.allowed-origins=${CORS_ALLOWED_ORIGINS:http://localhost:5173}

app.seed.admin.name=${APP_SEED_ADMIN_NAME:Administrador}
app.seed.admin.email=${APP_SEED_ADMIN_EMAIL:admin@gggg.com}
app.seed.admin.password=${APP_SEED_ADMIN_PASSWORD:admin@gggg.com}
