/** Curated emojis for personal finance categories; `keywords` used for PT-BR search. */
export type EmojiCatalogEntry = { emoji: string; keywords: string[] }

export const EMOJI_CATALOG: EmojiCatalogEntry[] = [
  { emoji: '🏠', keywords: ['casa', 'moradia', 'lar', 'home', 'apartamento'] },
  { emoji: '🍽️', keywords: ['comida', 'alimentação', 'alimentacao', 'restaurante', 'mercado'] },
  { emoji: '🛒', keywords: ['mercado', 'compras', 'supermercado'] },
  { emoji: '🚗', keywords: ['carro', 'transporte', 'uber', 'combustível', 'combustivel'] },
  { emoji: '🚌', keywords: ['ônibus', 'onibus', 'transporte', 'público'] },
  { emoji: '✈️', keywords: ['viagem', 'passagem', 'aéreo'] },
  { emoji: '⚕️', keywords: ['saúde', 'saude', 'médico', 'medico', 'farmácia', 'farmacia'] },
  { emoji: '💊', keywords: ['remédio', 'remedio', 'farmácia'] },
  { emoji: '🎉', keywords: ['lazer', 'festa', 'diversão'] },
  { emoji: '🎬', keywords: ['cinema', 'streaming', 'filme'] },
  { emoji: '🎮', keywords: ['jogo', 'games', 'lazer'] },
  { emoji: '📚', keywords: ['educação', 'educacao', 'curso', 'livro', 'escola'] },
  { emoji: '🎓', keywords: ['faculdade', 'universidade', 'estudo'] },
  { emoji: '📄', keywords: ['contas', 'boleto', 'documento'] },
  { emoji: '💡', keywords: ['luz', 'energia', 'elétrica'] },
  { emoji: '💧', keywords: ['água', 'agua', 'sanepar'] },
  { emoji: '📱', keywords: ['celular', 'telefone', 'internet'] },
  { emoji: '🌐', keywords: ['internet', 'wifi', 'provedor'] },
  { emoji: '👕', keywords: ['roupa', 'vestuário', 'moda'] },
  { emoji: '💄', keywords: ['beleza', 'cosméticos'] },
  { emoji: '🐕', keywords: ['pet', 'animal', 'veterinário'] },
  { emoji: '👶', keywords: ['bebê', 'bebe', 'filho', 'infantil'] },
  { emoji: '🎁', keywords: ['presente', 'doação'] },
  { emoji: '💼', keywords: ['trabalho', 'salário', 'escritório'] },
  { emoji: '💻', keywords: ['freelance', 'notebook', 'tech', 'software'] },
  { emoji: '💰', keywords: ['dinheiro', 'poupança', 'financeiro'] },
  { emoji: '🐷', keywords: ['porquinho', 'economia', 'poupança'] },
  { emoji: '💳', keywords: ['cartão', 'cartao', 'crédito'] },
  { emoji: '🏦', keywords: ['banco', 'financiamento'] },
  { emoji: '📈', keywords: ['investimento', 'bolsa'] },
  { emoji: '📉', keywords: ['perda', 'imposto'] },
  { emoji: '⚡', keywords: ['urgente', 'extra'] },
  { emoji: '🔧', keywords: ['reparo', 'manutenção', 'conserto'] },
  { emoji: '🛋️', keywords: ['móveis', 'moveis', 'decoração'] },
  { emoji: '☕', keywords: ['café', 'cafe', 'lanche'] },
  { emoji: '🍕', keywords: ['pizza', 'delivery'] },
  { emoji: '🏋️', keywords: ['academia', 'fitness', 'esporte'] },
  { emoji: '⚽', keywords: ['esporte', 'futebol'] },
  { emoji: '🎵', keywords: ['música', 'musica', 'show'] },
  { emoji: '📷', keywords: ['foto', 'equipamento'] },
  { emoji: '🚲', keywords: ['bike', 'bicicleta'] },
  { emoji: '🅿️', keywords: ['estacionamento'] },
  { emoji: '⛽', keywords: ['gasolina', 'combustível'] },
  { emoji: '🛡️', keywords: ['seguro', 'proteção'] },
  { emoji: '🧾', keywords: ['nota', 'fiscal', 'imposto'] },
  { emoji: '🏖️', keywords: ['praia', 'férias', 'ferias'] },
  { emoji: '🏨', keywords: ['hotel', 'hospedagem'] },
  { emoji: '🍔', keywords: ['fast', 'food'] },
  { emoji: '🥗', keywords: ['salada', 'saudável'] },
  { emoji: '🍼', keywords: ['bebê', 'fralda'] },
  { emoji: '🧹', keywords: ['limpeza', 'faxina'] },
  { emoji: '🔑', keywords: ['aluguel', 'chave', 'imóvel'] },
  { emoji: '🏗️', keywords: ['obra', 'reforma'] },
  { emoji: '💸', keywords: ['gasto', 'despesa'] },
  { emoji: '🪙', keywords: ['moeda', 'troco'] },
  { emoji: '💵', keywords: ['dinheiro', 'nota'] },
  { emoji: '🧸', keywords: ['brinquedo', 'criança'] },
  { emoji: '📦', keywords: ['frete', 'correio', 'compra online'] },
  { emoji: '🎫', keywords: ['ingresso', 'evento'] },
  { emoji: '🍷', keywords: ['bebida', 'bar'] },
  { emoji: '🌮', keywords: ['comida', 'mexicana'] },
  { emoji: '🥑', keywords: ['orgânico', 'saúde'] },
  { emoji: '🏥', keywords: ['hospital', 'clínica'] },
  { emoji: '🦷', keywords: ['dentista', 'odonto'] },
  { emoji: '👓', keywords: ['óculos', 'visão'] },
  { emoji: '🎨', keywords: ['arte', 'hobby'] },
  { emoji: '📌', keywords: ['outros', 'diversos'] },
  { emoji: '⭐', keywords: ['favorito', 'extra'] },
  { emoji: '❤️', keywords: ['doação', 'caridade'] },
  { emoji: '🌱', keywords: ['jardim', 'planta'] },
  { emoji: '🔋', keywords: ['eletrônicos', 'pilha'] },
  { emoji: '🖨️', keywords: ['impressão', 'papelaria'] },
  { emoji: '📮', keywords: ['correios', 'envio'] },
  { emoji: '🧴', keywords: ['higiene', 'banho'] },
  { emoji: '🚿', keywords: ['água', 'gás', 'banho'] },
  { emoji: '🛏️', keywords: ['cama', 'quarto'] },
  { emoji: '🍳', keywords: ['cozinha', 'utensílio'] },
  { emoji: '🥖', keywords: ['padaria', 'pão'] },
  { emoji: '🍎', keywords: ['fruta', 'feira'] },
  { emoji: '🍫', keywords: ['doce', 'sobremesa'] },
  { emoji: '🎂', keywords: ['aniversário', 'bolo'] },
  { emoji: '🏆', keywords: ['prêmio', 'bonus'] },
  { emoji: '🤑', keywords: ['renda', 'extra', 'ganho'] },
  { emoji: '🧑‍💻', keywords: ['dev', 'remoto', 'home office'] },
  { emoji: '💹', keywords: ['dividendos', 'rendimento'] },
  { emoji: '🎰', keywords: ['sorte', 'loteria'] },
]
